#!/bin/bash
if [ -f "/var/log/apt/history.log" -a -f "/var/log/dpkg.log" ]; then
aptlasttime=$(cat /var/log/apt/history.log |tail -n 1)
dpkglasttime=$(cat /var/log/dpkg.log |tail -n 1 | awk '{print $1,$2}')

checkDate=$(echo "${aptlasttime}" | grep -a "End-Date" | wc -l)

if [ "$checkDate" == "0" ]
then
	aptlasttime=${dpkglasttime}
else
	aptlasttime=$(echo "${aptlasttime}" | sed 's/End-Date: //g')
fi

ns1=$(date --date "$aptlasttime" +%s%N)
ns2=$(date --date "$dpkglasttime" +%s%N)

result=$(bc <<< "($ns2 - $ns1) / 1000000000")

if [ "${result}" -gt 1 ]
then
	aptlasttime=$(sed 's#  # #' <<< "${aptlasttime}")	
case $DPKG_HOOK_ACTION in
	install|unpack)
	
	while read packageFullName version; 
	do
		oldIFS=$IFS
		IFS=':'
	   	read -a pkgname <<< "${packageFullName}"
	   	IFS=$oldIFS
       		/usr/bin/deepin-app-store-pkgcache -i ${pkgname[0]} $version
	done < <(sed -n "/${aptlasttime}/, /*/p" /var/log/dpkg.log | grep -aE 'install |upgrade ' | awk '{print $4,$6}')
	;;
   	remove|purge)

	while read packageFullName version; 
	do
	   	oldIFS=$IFS
       		IFS=':'
	   	read -a pkgname <<< "${packageFullName}"
	   	IFS=$oldIFS
       		/usr/bin/deepin-app-store-pkgcache -r ${pkgname[0]} $version
	done < <(sed -n "/${aptlasttime}/, /*/p" /var/log/dpkg.log | grep -a 'remove ' | awk '{print $4,$5}')
	;;
esac

else
	case $DPKG_HOOK_ACTION in
	install|unpack)
   	pkginstall=$(cat /var/log/apt/history.log |grep -aE 'Install:|Upgrade:|Downgrade:'| tail -n 1 | sed 's/Install://g' | sed 's/Upgrade://g' | sed 's/Downgrade://g')

    	lastCmdLine=$(cat /var/log/apt/history.log |grep -an 'Commandline:'| tail -n 1 | cut -d':' -f1)
    	lastUpgradeLine=$(cat /var/log/apt/history.log |grep -anE 'Upgrade:|Downgrade:'| tail -n 1 | cut -d':' -f1)

    	if [[ $lastUpgradeLine > $lastCmdLine ]]
    	then
        IN=$pkginstall
        singlePkgCnt=$(echo $IN | tr ":" "\n"| wc -w)
        if [ "$singlePkgCnt" -gt 4 ]
        then
            	/usr/bin/deepin-app-store-pkgcache -c
        else
	       	arrpkgname=$(echo $IN | tr ":" "\n")
	       	read -a pkgname <<< "${arrpkgname[0]}"
	       	pkgversion=$(echo $pkginstall | grep -Po '(?<=\().*(?=\))'|awk -F "," '{print $NF}' | sed 's/ //g')
            	/usr/bin/deepin-app-store-pkgcache -i $pkgname $pkgversion
        fi	   
        
    else
	   IFS=',' read -ra ADDR <<< "$pkginstall"
	   for arrAllDetail in "${ADDR[@]}"; do
		result=$(echo $arrAllDetail)
		if [[ "$result" != "" ]] 
		then
			IN=$arrAllDetail
			arrpkgname=$(echo $IN | tr ":" "\n")
			read -a pkgname <<< "${arrpkgname[0]}"
			pkgversion=$(echo $arrAllDetail | grep -Po '(?<=\().*(?=\))'|awk -F "," '{print $NF}' | sed 's/ //g')

			/usr/bin/deepin-app-store-pkgcache -i $pkgname $pkgversion
    		fi
	   done	
    fi

	;;

   	remove|purge)

	pkginstall=$(cat /var/log/apt/history.log |grep -a 'Remove:' | tail -n 1 | sed 's/Remove://g')

	IFS=',' read -ra ADDR <<< "$pkginstall"
	for arrAllDetail in "${ADDR[@]}"; do
		result=$(echo $arrAllDetail)
		if [[ "$result" != "" ]] 
		then
			IN=$arrAllDetail
			arrpkgname=$(echo $IN | tr ":" "\n")
			read -a pkgname <<< "${arrpkgname[0]}"
			pkgversion=$(echo $arrAllDetail | grep -Po '(?<=\().*(?=\))')
			/usr/bin/deepin-app-store-pkgcache -r $pkgname $pkgversion
    		fi
	done	
	;;
esac

fi

else
	/usr/bin/deepin-app-store-pkgcache -u
fi

