#!/bin/bash
if [ -f "/var/log/apt/history.log" -a -f "/var/log/dpkg.log" ]; then
aptlasttime=$(cat /var/log/apt/history.log |tail -n 1)
dpkglasttime=$(cat /var/log/dpkg.log |tail -n 1 | awk '{print $1,$2}')

checkDate=$(echo "${aptlasttime}" | grep -a "End-Date" | wc -l)

if [ "$checkDate" == "0" ]
then
	aptlasttime=${dpkglasttime}
else
	aptlasttime=$(echo "${aptlasttime}" | sed 's/End-Date: //g')
fi

ns1=$(date --date "$aptlasttime" +%s%N)
ns2=$(date --date "$dpkglasttime" +%s%N)

result=$(bc <<< "($ns2 - $ns1) / 1000000000")

if [ "${result}" -gt 1 ]
then
	aptlasttime=$(sed 's#  # #' <<< "${aptlasttime}")	
case $DPKG_HOOK_ACTION in
	install|unpack)
	
	while read packageFullName version; 
	do
		oldIFS=$IFS
		IFS=':'
	   	read -a pkgname <<< "${packageFullName}"
	   	IFS=$oldIFS
       		/usr/bin/deepin-app-store-pkgcache -i ${pkgname[0]} $version
	done < <(sed -n "/${aptlasttime}/, /*/p" /var/log/dpkg.log | grep -aE 'install |upgrade ' | awk '{print $4,$6}')
	;;
   	remove|purge)

	while read packageFullName version; 
	do
	   	oldIFS=$IFS
       		IFS=':'
	   	read -a pkgname <<< "${packageFullName}"
	   	IFS=$oldIFS
       		/usr/bin/deepin-app-store-pkgcache -r ${pkgname[0]} $version
	done < <(sed -n "/${aptlasttime}/, /*/p" /var/log/dpkg.log | grep -a 'remove ' | awk '{print $4,$5}')
	;;
esac

else
    case $DPKG_HOOK_ACTION in
	install|unpack|remove|purge)

    	lastCmdLine=$(cat /var/log/apt/history.log |grep -an 'Commandline:'| tail -n 1 | cut -d':' -f1)
    	lastInstallLine=$(cat /var/log/apt/history.log |grep -an 'Install:'| tail -n 1 | cut -d':' -f1)
    	lastRemoveLine=$(cat /var/log/apt/history.log |grep -anE 'Remove:'| tail -n 1 | cut -d':' -f1)
    	lastUpgradeLine=$(cat /var/log/apt/history.log |grep -anE 'Upgrade:'| tail -n 1 | cut -d':' -f1)
    	lastDowngradeLine=$(cat /var/log/apt/history.log |grep -anE 'Downgrade:'| tail -n 1 | cut -d':' -f1)

    	if [[ $lastUpgradeLine > $lastCmdLine ]]
    	then
        	pkginstall=$(cat /var/log/apt/history.log |grep -aE 'Upgrade:'| tail -n 1 | sed 's/Install://g' | sed 's/Upgrade://g' | sed 's/Downgrade://g')
    		i=0
		pkgtmp=""
		for pkginfolist in $(echo $pkginstall | grep -Po '(.*?) \((.*?), (.*?)\)'); do
		if [[ i -eq 0 || i%4 -eq 0 ]];then
		pkgtmp="${pkginfolist}"
  		fi
  		if [[ i%4 -eq 2 ]];then

		IFS=':' read -ra arrpkgname <<< "${pkgtmp}"
		IFS=')' read -ra arrversion <<< "${pkginfolist}"

		pkgname="${arrpkgname[0]}"
		pkgversion="${arrversion[0]}"

    		/usr/bin/deepin-app-store-pkgcache -i $pkgname $pkgversion

  		fi
  		i=$((i+1))
		done
	fi

    	if [[ $lastDowngradeLine > $lastCmdLine ]]
    	then
        	pkginstall=$(cat /var/log/apt/history.log |grep -aE 'Downgrade:'| tail -n 1 | sed 's/Install://g' | sed 's/Upgrade://g' | sed 's/Downgrade://g')
  		i=0
		pkgtmp=""
		for pkginfolist in $(echo $pkginstall | grep -Po '(.*?) \((.*?), (.*?)\)'); do
	  	if [[ i -eq 0 || i%4 -eq 0 ]];then
	    	pkgtmp="${pkginfolist}"
  		fi
	  	if [[ i%4 -eq 2 ]];then

		IFS=':' read -ra arrpkgname <<< "${pkgtmp}"
		IFS=')' read -ra arrversion <<< "${pkginfolist}"

		pkgname="${arrpkgname[0]}"
		pkgversion="${arrversion[0]}"

    		/usr/bin/deepin-app-store-pkgcache -i $pkgname $pkgversion

  		fi
  		i=$((i+1))
		done  	
  	fi	   
        
    	if [[ $lastInstallLine > $lastCmdLine ]]
    	then
        	pkginstall=$(cat /var/log/apt/history.log |grep -a 'Install:'| tail -n 1 | sed 's/Install://g' | sed 's/Upgrade://g' | sed 's/Downgrade://g')
		IFS=',' read -ra ADDR <<< "$pkginstall"
	    	for arrAllDetail in "${ADDR[@]}"; do
			result=$(echo $arrAllDetail)
			if [[ "$result" != "" ]]
			then
				IN=$arrAllDetail
				pkgCnt=$(echo $IN | tr ":" "\n"| wc -w)
        			if [ "$pkgCnt" == "3" ]
        			then
					arrpkgname=$(echo $IN | tr ":" "\n")
					read -a pkgname <<< "${arrpkgname[0]}"
					pkgversion=$(echo $IN | grep -Po '(?<=\().*(?=\))'|awk -F "," '{print $NF}' | sed 's/ //g')
					if [[ "$pkgversion" != "" ]] 
		  			then
						/usr/bin/deepin-app-store-pkgcache -i $pkgname $pkgversion
					else
						IFS=':' read -ra arrpkgname <<< "${IN}"
						IFS='(' read -ra arrpkgname2 <<< "${arrpkgname[1]}"

						pkgname=${arrpkgname[0]}
						pkgversion=${arrpkgname2[1]}
						/usr/bin/deepin-app-store-pkgcache -i $pkgname $pkgversion
	
					fi
				elif [ "$pkgCnt" == "4" ]
				then
						IFS=' ' read -ra pkgnameArr <<< "${IN}"
						IFS=':' read -ra pkgnameBase <<< ""${pkgnameArr[0]}
						IFS='(' read -ra pkgversionArr <<< "${pkgnameArr[1]}"
						
						pkgname=${pkgnameBase[0]}
						pkgversion=${pkgversionArr[1]}
						/usr/bin/deepin-app-store-pkgcache -i $pkgname $pkgversion

					
				fi
    			fi
	   	done

    	fi

    if [[ $lastRemoveLine > $lastCmdLine ]]
    	then
	   pkginstall=$(cat /var/log/apt/history.log |grep -a 'Remove:' | tail -n 1 | sed 's/Remove://g')

	   IFS=',' read -ra ADDR <<< "$pkginstall"
	   for arrAllDetail in "${ADDR[@]}"; do
		result=$(echo $arrAllDetail)
		  if [[ "$result" != "" ]] 
		  then
			IN=$arrAllDetail
			arrpkgname=$(echo $IN | tr ":" "\n")
			read -a pkgname <<< "${arrpkgname[0]}"
			pkgversion=$(echo $arrAllDetail | grep -Po '(?<=\().*(?=\))')
			/usr/bin/deepin-app-store-pkgcache -r $pkgname $pkgversion
    		  fi
	   done	
    fi

	;;
esac

fi

else
	/usr/bin/deepin-app-store-pkgcache -u
fi

